---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase-deployment
  namespace: voltron-demo
spec:
  selector:
    matchLabels:
      app: metabase
  replicas: 1
  template:
    metadata:
      labels:
        app: metabase
    spec:
      nodeSelector:
        size: 'huge'
      containers:
      - name: metabase
        image: metabase/metabase
        envFrom:
          - configMapRef:
              name: metabase-config
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metabase-config
  namespace: voltron-demo
  labels:
    app: metabase
data:
  MB_DB_TYPE: postgres
  MB_DB_DBNAME: metabase
  MB_DB_PORT: '5432'
  MB_DB_USER: postgresadmin
  MB_DB_PASS: admin123
  MB_DB_HOST: postgres-db


---
apiVersion: v1
kind: Service
metadata:
  name: metabase
  namespace: voltron-demo
spec:
  selector:
    app: metabase
  ports:
    - protocol: TCP
      port: 3000
  type: LoadBalancer
  loadBalancerIP: 192.168.87.157