name: Publish VoltronSecurity package to PyPI and TestPyPI

on: push

jobs:
  build-and-publish:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    - name: Install build tools
      run: >-
        python3 -m pip install build --user
    - name: Build package
      run: >-
        python3 -m build --sdist --wheel --outdir dist/
    - name: Publish to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_TEST_TOKEN }}
        repository-url: https://test.pypi.org/legacy
    - name: Publish to Prod PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{secrets.PYPI_PUBLISH_TOKEN }}